name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # This enables manual trigger from the GitHub Actions interface


jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.9  # Using Python 3.8.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyinstaller

      # Step 4: Build the executable
      - name: Build exe
        run: |
          pyinstaller --onefile --noupx --exclude-module tkinter --exclude-module numpy defensecrawler.py # Build defensecrawler.py into a single executable

      # Step 5: Upload the built executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: WindowsExecutable
          path: dist/defensecrawler.exe  # Ensure this matches the output file path
